name: Build RayTraceAntiXray

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make compile.sh executable
        run: chmod +x compile.sh

      - name: Build plugin
        run: ./compile.sh

      - name: List files for debugging
        run: ls -l

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: RayTraceAntiXray
          path: RayTraceAntiXray.jar
          if-no-files-found: error
